"""User email unique

Revision ID: 5b725489fde2
Revises: 9e19b0689ec5
Create Date: 2023-05-28 19:11:25.720542

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "5b725489fde2"
down_revision = "9e19b0689ec5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")  # type:ignore
    # ### end Alembic commands ###
