"""User relationship

Revision ID: be475de9d347
Revises: 4c4c661ebc59
Create Date: 2023-05-26 10:30:25.924804

"""


# revision identifiers, used by Alembic.
revision = "be475de9d347"
down_revision = "4c4c661ebc59"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
