"""Script table 2

Revision ID: 2569e8b3c535
Revises: 0409eb25f559
Create Date: 2023-05-22 19:30:01.354783

"""


# revision identifiers, used by Alembic.
revision = "2569e8b3c535"
down_revision = "0409eb25f559"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
