"""Refresh tokens table

Revision ID: 80b2f0e4ba83
Revises: 5b725489fde2
Create Date: 2023-06-07 17:06:26.245160

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "80b2f0e4ba83"
down_revision = "5b725489fde2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.Text, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("refresh_tokens")
    # ### end Alembic commands ###
