"""User increase password field length 30 -> 100 2

Revision ID: 9e19b0689ec5
Revises: cc550189aaeb
Create Date: 2023-05-26 10:34:49.510205

"""


# revision identifiers, used by Alembic.
revision = "9e19b0689ec5"
down_revision = "cc550189aaeb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
