"""Refresh string field to text

Revision ID: bebc44616f68
Revises: 80b2f0e4ba83
Create Date: 2023-06-08 11:56:32.912690

"""


# revision identifiers, used by Alembic.
revision = "bebc44616f68"
down_revision = "80b2f0e4ba83"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
