"""Script table 5 test

Revision ID: ff2086bf7dbe
Revises: 612519636ad9
Create Date: 2023-05-22 19:52:15.923279

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ff2086bf7dbe"
down_revision = "612519636ad9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scripts", sa.Column("created_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scripts", "created_at")
    # ### end Alembic commands ###
