"""init

Revision ID: 5b9db61f86b5
Revises: 
Create Date: 2024-01-03 13:04:46.906573

"""
from alembic import op
import sqlalchemy as sa

from zametka.notes.infrastructure.db.models import Note

# revision identifiers, used by Alembic.
revision = "5b9db61f86b5"
down_revision = None
branch_labels = None
depends_on = None

INDEX_NAME = "notes_title_trgm_idx"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("identity_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=40), nullable=False),
        sa.Column("last_name", sa.String(length=60), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("identity_id"),
    )
    op.create_table(
        "notes",
        sa.Column("note_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("text", sa.String(length=60000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.identity_id"],
        ),
        sa.PrimaryKeyConstraint("note_id"),
    )
    # ### end Alembic commands ###

    conn = op.get_bind()

    conn.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))

    index = sa.Index(
        INDEX_NAME,
        sa.func.coalesce(Note.title, "").label("columns"),
        postgresql_using="gin",
        postgresql_ops={
            "columns": "gin_trgm_ops",
        },
    )

    op.create_index(
        INDEX_NAME,
        "notes",
        index.expressions,  # type:ignore
        postgresql_using="gin",
        postgresql_ops={"columns": "gin_trgm_ops"},
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notes")
    op.drop_table("users")
    # ### end Alembic commands ###
