"""User increase password field length 30 -> 100

Revision ID: cc550189aaeb
Revises: be475de9d347
Create Date: 2023-05-26 10:32:49.705876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cc550189aaeb"
down_revision = "be475de9d347"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
