"""Script table

Revision ID: 0409eb25f559
Revises: 
Create Date: 2023-05-22 19:18:04.092744

"""


# revision identifiers, used by Alembic.
revision = "0409eb25f559"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
