"""User

Revision ID: 4c4c661ebc59
Revises: 6a2ab4ef3b89
Create Date: 2023-05-26 10:17:25.937813

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4c4c661ebc59"
down_revision = "6a2ab4ef3b89"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=60), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("first_name", sa.String(length=40), nullable=False),
        sa.Column("last_name", sa.String(length=60), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("notes", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "notes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "notes", type_="foreignkey")  # type:ignore
    op.drop_column("notes", "user_id")
    op.drop_table("users")
    # ### end Alembic commands ###
