"""Refresh tokens table

Revision ID: 80b2f0e4ba83
Revises: 5b725489fde2
Create Date: 2023-06-07 17:06:26.245160

"""

# revision identifiers, used by Alembic.
revision = "80b2f0e4ba83"
down_revision = "5b725489fde2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    pass
