"""Script table 3

Revision ID: 8b6f376f7f8f
Revises: 2569e8b3c535
Create Date: 2023-05-22 19:32:47.412065

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import text, Index, func

from zametka.infrastructure.db.models.notes import Note

# revision identifiers, used by Alembic.
revision = "8b6f376f7f8f"
down_revision = "2569e8b3c535"
branch_labels = None
depends_on = None

INDEX_NAME = "notes_title_trgm_idx"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    conn = op.get_bind()

    conn.execute(text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))

    index = Index(
        INDEX_NAME,
        func.coalesce(Note.title, "").label("columns"),
        postgresql_using="gin",
        postgresql_ops={
            "columns": "gin_trgm_ops",
        },
    )

    op.create_index(
        INDEX_NAME,
        "notes",
        index.expressions,  # type:ignore
        postgresql_using="gin",
        postgresql_ops={"columns": "gin_trgm_ops"},
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        INDEX_NAME,
        table_name="notes",
        postgresql_using="gin",
        postgresql_ops={"columns": "gin_trgm_ops"},
    )

    op.drop_table("notes")

    conn = op.get_bind()

    conn.execute(text("DROP EXTENSION pg_trgm"))

    # ### end Alembic commands ###
